
DROP TABLE IF EXISTS Text;
DROP TABLE IF EXISTS Revision;
DROP TABLE IF EXISTS Page;

CREATE TABLE Text (
    text_id INTEGER PRIMARY KEY AUTOINCREMENT,
    content TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Revision (
    rev_id INTEGER PRIMARY KEY AUTOINCREMENT,
    page_id INTEGER NOT NULL,
    text_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (page_id) REFERENCES Page(page_id) ON DELETE CASCADE,
    FOREIGN KEY (text_id) REFERENCES Text(text_id) ON DELETE CASCADE
);

CREATE TABLE Page (
    page_id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    latest_rev INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (latest_rev) REFERENCES Revision(rev_id) ON DELETE CASCADE
);
-- "case insensitive" index
CREATE UNIQUE INDEX page_title_upper ON Page (UPPER(title));

